// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guknrnphffabtmhkglvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1a25ybnBoZmZhYnRtaGtnbHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjQwNjIsImV4cCI6MjA2ODM0MDA2Mn0.gYZ-9MbEq-aXm317pAjZkQcG3qZE76ma_ZBAfV-rW20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});